---

- hosts: all
  become: true
  tasks: 
  
  - name: updating repositories
    yum:
      update_cache: yes


  - name: installing apache2 package
    yum:
      name: httpd
      state: latest
  
  - name: installing net-tools package
    yum:
      name: net-tools
      state: latest 
