---

- hosts: all
  become: true
  tasks: 
  
  - name: removing apache2 package
    tags: centos
    yum:
      name: httpd
      state: absent
  
  - name: removing net-tools package
    yum:
      name: net-tools
      state: absent 
